os: linux
dist: trusty
language: python
services: docker

env:
  global:
    - BASE=compdatasci/octave-desktop:latest
    - VERSION=17F

before_script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -n $(git log --since $(docker inspect $BASE | grep Created | perl -e "s/.+\"([\d-:T]+).+$/\$1/g" -p)) &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml -e image -e WELCOME)" ]] ||
    (docker build --tag ams529/desktop:$VERSION
                  --tag ams529/desktop:latest . &&
     docker push ams529/desktop &&
     touch success)'
  # Test startup scripts
  - './ams529_desktop.py -d -n && docker stop $(docker ps -q) &&
     ./ams529_jupyter.py -d -n && docker stop $(docker ps -q)'
  - docker images
